name:                haskell-brickudoku
version:             0.1.0.0
github:              "thecentury/haskell-brickudoku"
license:             MIT
author:              "thecentury"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thecentury/haskell-brickudoku#readme>

tested-with: GHC==9.6.1

dependencies:
  - base >= 4.7 && < 5
  - brick
  - containers
  - extra
  - linear
  - lens
  - random
  - transformers
  - vty
  - mtl
  - stm
  - array
  - linear

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  haskell-brickudoku-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-brickudoku

tests:
  haskell-brickudoku-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-brickudoku